spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/maxmessenger
    username: "user"
    password: "pass"
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
